services:
  frontend:
    build:
      context: ./frontend
    networks:
      - app-network
    volumes:
      - frontend-build:/app/dist/browser
    # No restart policy needed since it will just build the application

  backend:
    build:
      context: ./backend
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    networks:
      - app-network
    restart: always
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - frontend-build:/usr/share/nginx/html
    ports:
      - "80:80"
    networks:
      - app-network
    restart: always
    depends_on:
      - frontend

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
  frontend-build:
